github: Don't archive artifacts
Don't archive code coverage and test log artifacts.  One, I haven't used
the uploaded files for analysis or debugging, and, two, these steps are
failing.

	Error: Failed to CreateArtifact: Received non-retryable error:
	Failed request: (409) Conflict: an artifact with this name already
	exists on the workflow run

Signed-off-by: Tom Hromatka <tom.hromatka@oracle.com>